version: '3.8'

services:
  # PostgreSQL service
  db:
    image: postgres:13  # Use the desired version of PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: sfe
      POSTGRES_PASSWORD: sfe
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"  # Adjust the port if needed
    environment:
      - DATABASE_URL=postgresql://sfe:sfe@db/backend
    volumes:
      - .:/app

volumes:
  pg_data:  # Volume for PostgreSQL data persistence
