name: pytest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest psycopg2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up PostgreSQL database
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE mydatabase;"
          alembic upgrade head

      - name: Set DATABASE_URL environment variable
        run: echo "export DATABASE_URL=postgresql://postgres:password@localhost:5432/mydatabase" >> $GITHUB_ENV

      - name: Run pytest tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: python -m pytest
